//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Editor.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MENUDLG                     310
#define IDD_DLGTRANS                    322
#define IDD_TOOLDLG                     336
#define IDD_MESHDLG                     342
#define IDD_FBXDLG                      344
#define IDD_KM3DLG                      346
#define IDD_UNITDLG                     348
#define IDD_FORCEDLG                    350
#define IDD_TERRAINDLG                  353
#define IDD_DIALOG1                     355
#define IDD_UNITLISTDLG                 355
#define IDC_MENUTAB                     1000
#define IDC_FBXLOADBTN                  1001
#define IDC_KM3LOAD                     1001
#define IDC_DIFFPATH                    1006
#define IDC_NORMPATH                    1007
#define IDC_SPECPATH                    1008
#define IDC_EMISPATH                    1009
#define IDC_KM3ACSSAVE                  1011
#define IDC_KM3ACASAVE                  1012
#define IDC_POSX                        1013
#define IDC_POSY                        1014
#define IDC_POSZ                        1015
#define IDC_ROTX                        1016
#define IDC_ROTY                        1017
#define IDC_ROTZ                        1018
#define IDC_SCALX                       1019
#define IDC_SCALY                       1020
#define IDC_SCALZ                       1021
#define IDC_TOKM3                       1025
#define IDC_KM3ACADDBTN                 1025
#define IDC_KM3ACDELBTN                 1026
#define IDC_FBX2KM3TAB                  1026
#define IDC_FBXLIST                     1029
#define IDC_POSX2                       1031
#define IDC_KM3LIST                     1031
#define IDC_POSY2                       1032
#define IDC_POSZ2                       1033
#define IDC_ROTX2                       1034
#define IDC_ROTY2                       1035
#define IDC_ROTZ2                       1036
#define IDC_KM3ACCOMBO                  1036
#define IDC_SCALX2                      1037
#define IDC_KM3ACSTART                  1037
#define IDC_SCALY2                      1038
#define IDC_KM3ACEND                    1038
#define IDC_KM3ACNAME                   1039
#define IDC_SCALZ2                      1039
#define IDC_DIFFBTN                     1040
#define IDC_NORMBTN                     1041
#define IDC_ACFILENAME                  1042
#define IDC_SPECBTN                     1042
#define IDC_EMISBTN                     1043
#define IDC_DIFFPATHK                   1046
#define IDC_NORMPATHK                   1047
#define IDC_SPECPATHK                   1048
#define IDC_EMISPATHK                   1049
#define IDC_DIFFBTNK                    1050
#define IDC_NORMBTNK                    1051
#define IDC_SPECBTNK                    1052
#define IDC_FORCELIST                   1052
#define IDC_EMISBTNK                    1053
#define IDC_FORCENAME                   1053
#define IDC_FORCECOLOR                  1058
#define IDC_FORKM3LIST                  1059
#define IDC_KM3RESETBTN                 1060
#define IDC_SFSBTN                      1061
#define IDC_AFSBTN                      1062
#define IDC_LISTUPBTN                   1063
#define IDC_KM3PLAYBTN                  1065
#define IDC_KM3PAUBTN                   1066
#define IDC_UNITKM3LIST                 1066
#define IDC_UNITSELECTLIST              1067
#define IDC_RENDELETEBTN                1068
#define IDC_RENINSERTBTN                1069
#define IDC_RENRESETBTN                 1070
#define IDC_KM3PREVBTN                  1071
#define IDC_KM3NEXTBTN                  1073
#define IDC_UNITLOADBTN                 1073
#define IDC_UNITSAVEBTN                 1074
#define IDC_RENRESTARTBTN               1075
#define IDC_ULEDIT                      1076
#define IDC_UREDIT                      1077
#define IDC_KUNITXINFO                  1078
#define IDC_KUNITYINFO                  1079
#define IDC_TERCLEAR                    1080
#define IDC_KUNITZINFO                  1080
#define IDC_UNITNAMEINFO                1081
#define IDC_TERSAVE                     1081
#define IDC_WNONEBTN                    1082
#define IDC_TERUNITLIST                 1082
#define IDC_WINSTBTN                    1083
#define IDC_WSHOTBTN                    1084
#define IDC_TERLOAD                     1084
#define IDC_STATELOAD                   1085
#define IDC_UNITNONEBTN                 1085
#define IDC_STATESAVE                   1086
#define IDC_UNITENEMYBTN                1086
#define IDC_STATECLEAR                  1087
#define IDC_UNITUSERBTN                 1087
#define IDC_UNITINFOHP                  1088
#define IDC_UNITINFOINTERVAL            1089
#define IDC_UNITINFOSCORE               1090
#define IDC_UNITPOSXEDIT                1092
#define IDC_UNITPOSYEDIT                1093
#define IDC_UNITPOSZEDIT                1094
#define IDC_TERSPLITX                   1095
#define IDC_TERSPLITZ                   1096
#define IDC_TERSCALEX                   1097
#define IDC_TERSCALEZ                   1098
#define IDC_TERTEXPATH                  1099
#define IDC_TERCOVERTEX                 1100
#define IDC_TERNAME                     1101
#define IDC_STATENAME                   1102
#define IDC_STATETERNAME                1103
#define IDC_TEREDITBTN                  1104
#define IDC_STATETERBTN                 1105
#define IDC_STATERESLIST                1106
#define IDC_UNITLIST                    1107
#define IDC_TERSETPLAY                  1108
#define IDC_UNITLINEAR                  1109
#define IDC_UNITROTATE                  1110
#define IDC_USCALEX                     1111
#define IDC_UNITSTATICPOSX              1111
#define IDC_USCALEY                     1112
#define IDC_UNITSTATICPOSY              1112
#define IDC_USCALEZ                     1113
#define IDC_UNITSTATICPOSZ              1113
#define IDC_UHP                         1114
#define IDC_UINTEVAL                    1115
#define IDC_USCORE                      1116
#define IDC_UNITROTXEDIT                1122
#define IDC_UNITROTYEDIT                1123
#define IDC_UNITROTZEDIT                1124
#define IDC_UNITSTATICROTX              1125
#define IDC_UNITSTATICROTY              1126
#define IDC_UNITSTATICROTZ              1127
#define IDC_TERNONERADIO                1119
#define IDC_TERENEMYRADIO               1120
#define IDC_TERUSERRADIO                1121

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        358
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
